[project]
name = "demand-forecasting"
version = "0.1.0"
requires-python = ">=3.10, <3.11"

dependencies = [
  "datasets>=4.3.0",
  "pandas>=2.3.3",
  "scikit-learn>=1.7.2",
  "statsmodels>=0.14.5",
  "torch>=2.0.0",
  "numpy>=1.24.0",
  "tqdm>=4.66.0",
  "pygrinder>=0.6.0",
]
