[project]
name = "demand-forecasting"
version = "0.1.0"
requires-python = ">=3.10, <3.11"

dependencies = [
  "datasets>=4.3.0",
  "pandas>=2.3.3",
  "scikit-learn>=1.7.2",
  "statsmodels>=0.14.5",
]
